config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'tasks#index'
  resources :tasks, except: %i[index]
  resources :subtasks, only: %i[create edit destroy]do
    patch :finished, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subtask.rb
# == Schema Information
#
# Table name: subtasks
#
#  id         :integer          not null, primary key
#  title      :string
#  done       :boolean
#  task_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Subtask < ApplicationRecord

  belongs_to :task

end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :text
#  remind_at  :datetime
#  priority   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Task < ApplicationRecord

  has_many :subtasks
  accepts_nested_attributes_for :subtasks

  enum priority: {
    low: 0,
    medium: 1,
    high: 2
  } 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/subtasks_controller.rb
class SubtasksController < ApplicationController

   skip_before_action :verify_authenticity_token

  def create
    @subtask = Subtask.new(subtask_params)
    respond_to do |format|
      format.js do
        if @subtask.save
          render json: { id: @subtask.id }
        end
      end
    end
  end

  def finished
    @subtask = Subtask.find(params[:id])
    @subtask.update(done: params[:done])
  end

  private

  def subtask_params
    {
      title: params[:title],
      task_id: params[:task_id]
    }
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :task, only: %i[show edit update destroy]

  def index
    @tasks = Task.all
  end

  def show
    render :edit
  end

  def new
    @task = Task.new
  end

  def edit; end

  def create
    @task = Task.create(task_params)
    redirect_to edit_task_path(@task)
  end

  def update
    if @task.update(task_params)
      redirect_to root_path
    else
      flash[:alert] = 'Somthing wrong, Record not save!'
    end
  end

  def destroy
    @task.destroy
    redirect_to root_path
  end

  private

  def task_params
    params.require(:task).permit(
      %i[
        id
        title
        body
        priority
        remind_at
      ]
    )
  end

  def task
    @task = Task.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subtasks_helper.rb
module SubtasksHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | TodoApp
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'

    - if content_for :styles
      = yield :styles

    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', media: 'all'
    = javascript_include_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js'
  body
    .container
      - if content_for? :header
        = yield :header
      - else
        = render '/layouts/partial/header.html.slim'

      = yield

      - if content_for? :modals
        = yield :modals

      - if content_for? :scripts 
        = yield :scripts

app/views/layouts/partial/_header.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container-fluid
    a.navbar-brand href="#{root_url}" Todo App
    = link_to 'Add Task', new_task_path, class: 'btn btn-primary add-task'
    button.navbar-toggler type="button" data-bs-toggle="collapse" data-bs-target="#nav" aria-controls="nav" aria-expanded="false" aria-label="Toggle navigation"
      span.navbar-toggler-icon
    .collapse.navbar-collapse id="nav"
      ul.navbar-nav
        li.navbar-item
          a.nav-link.active aria-current="page" href="#{root_url}" Home Page

app/views/subtasks/_new.html.slim
.modal.fade id='newSubtask' tabindex='-1'
  .modal-dialog
    .modal-content
      .modal-header
        h5 New Subtask
        button.btn-close type='button' data-bs-dismiss='modal' aria-label='close'
      .modal-body
        = hidden_field_tag :task_id, f.object.id
        label Title:
        input#subtask_title
      .modal-footer
        button.btn.btn-secondary data-bs-dismiss='modal' Close
        #saveSubtask.btn.btn-primary Save

javascript:
  $('#saveSubtask').on('click', () => {
    let url = '/subtasks'
    let task_id = $('#task_id').val()
    let title = $('#subtask_title').val()
    $('.btn-close').click()

    $.ajax({
      url,
      method: 'POST',
      data: {
        task_id,
        title
      },
    })
  })

app/views/tasks/_form.html.slim
.form-control
  .form-label
    = form.label :title
  = form.text_field :title, class: 'form-control'
  .form-label
    = form.label :body
  = form.text_area :body, class: 'form-control'
  .form-label
    = form.label :priority
  = form.select :priority, Task.priorities.keys, class: 'form-control'
  .mt-3
    .form-label
      = form.label :remind_at
    = form.datetime_local_field :remind_at
  - if form.object.id.present?
    .mt-3
      button.btn.btn-primary type='button' data-bs-toggle='modal' data-bs-target='#newSubtask' + Add subtask
  .mt-3
    = form.submit 'Save', class: 'btn btn-primary'

- content_for :modals do
  = render '/subtasks/new', f: form

app/views/tasks/_task_card.html.slim
.card-header
  .row
    .col-8
      .task-title = task.title
    .col-4
      .task-priority class="#{task.priority}" = task.priority 
.card-body
  p.card-text = task.body
  .mt-3
    - if task.subtasks.present?
      hr
      - task.subtasks.each do |sub|
        .form-check
          - if sub.done
            = check_box_tag "subtask-#{sub.id}", sub.id, checked: true
            = sub.title
          - else
            = check_box_tag "subtask-#{sub.id}", sub.id
            = sub.title
.card-footer
  - if task.remind_at.present?
    .row
      p.card-text.text-muted = task.remind_at
      hr
  .row
    .col-8
      = link_to 'Edit', task_path(task), class: 'btn btn-primary'
    .col-4
      = button_to 'Delete', task_path(task), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

app/views/tasks/edit.html.slim
.text-center.mt-2.mb-2
  h4 Edit Task
  = button_to 'Delete', tasks_path(@task), method: :delete

= form_with model: @task do |form|
  = render 'form', form: form

app/views/tasks/index.html.slim
- content_for :styles do
  = stylesheet_link_tag 'tasks'

- @tasks.each do |task|
  .card.mt-4.task-card
    = render 'task_card', task: task

javascript:
  $('.form-check').on('click', 'input', function() {
    let subtaskId = $(this).val()
    let done = $(this).is(':checked')
    let url = `/subtasks/${subtaskId}/finished`
    $.ajax({
      url,
      method: 'PATCH',
      data: {
      done
      }
    })
  })

app/views/tasks/new.html.slim
.text-center.mt-2.mb-2
  h4 New Task

= form_with model: @task do |form|
  = render 'form', form: form